//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR30.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsReports
    {
        public int IDTestQuestions { get; set; }
        public int IDTestingReport { get; set; }
        public Nullable<int> Answer { get; set; }
    
        public virtual TestingReport TestingReport { get; set; }
        public virtual TestQuestions TestQuestions { get; set; }
    }
}
