//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR30.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingReport
    {
        public int id { get; set; }
        public System.DateTime DateTesting { get; set; }
        public int IDStudent { get; set; }
        public System.TimeSpan TimeTesting { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
