//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR30.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestions
    {
        public int id { get; set; }
        public Nullable<int> IDTypeQuestions { get; set; }
        public string Question { get; set; }
        public string AnswerVariant1 { get; set; }
        public string AnswerVariant2 { get; set; }
        public string AnswerVariant3 { get; set; }
        public string AnswerVariant4 { get; set; }
        public Nullable<int> CorrectAnswer { get; set; }
    
        public virtual TypeQuestion TypeQuestion { get; set; }
    }
}
