//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR30.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestQuestions()
        {
            this.QuestionsReports = new HashSet<QuestionsReports>();
        }
    
        public int id { get; set; }
        public Nullable<int> IDTypeQuestions { get; set; }
        public string Question { get; set; }
        public string AnswerVariant1 { get; set; }
        public string AnswerVariant2 { get; set; }
        public string AnswerVariant3 { get; set; }
        public string AnswerVariant4 { get; set; }
        public Nullable<int> CorrectAnswer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionsReports> QuestionsReports { get; set; }
        public virtual TypeQuestion TypeQuestion { get; set; }
    }
}
